package com.mosl.hxcandle.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mosl.hxcandle.bean.LocalBleDevice;

import com.mosl.hxcandle.database.LocalBleDeviceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localBleDeviceDaoConfig;

    private final LocalBleDeviceDao localBleDeviceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localBleDeviceDaoConfig = daoConfigMap.get(LocalBleDeviceDao.class).clone();
        localBleDeviceDaoConfig.initIdentityScope(type);

        localBleDeviceDao = new LocalBleDeviceDao(localBleDeviceDaoConfig, this);

        registerDao(LocalBleDevice.class, localBleDeviceDao);
    }
    
    public void clear() {
        localBleDeviceDaoConfig.clearIdentityScope();
    }

    public LocalBleDeviceDao getLocalBleDeviceDao() {
        return localBleDeviceDao;
    }

}
